server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/resume_db
spring.datasource.username=root
spring.datasource.password=Vinu@12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# GROQ API KEY
groq.api.key=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